### PR TITLE
Robo scripting

### PR DESCRIPTION
**Pull request by EdwardS2013**
Pull request for the base 3 classes of the roboscripting library- CallReference, MethodHolder, PythonComms. SampleSubsystem is meant to showcase how these libraries can be used to store references to methods and motors. 

PythonComms-

Communicates with the simple python client on port 8080. Parses the received command with the token ":" and passes resulting String[] to CallReference. I.e "motors:testMotor1:set_power:0.5" would be parsed to [motors, testMotor1, set_power, 0.5] with all whitespace removed.

CallReference-

Contains three hashmaps which contain: 
<Method name, MethodHolder object reference>,
<Motor name, CANTalon246 object reference>,
<Command name, Command object reference>. 

Handles the received String[] from PythonComms and performs appropriate set/get functions.

MethodHolder- 

Contains two methods which must be user-specified. CallMethod is called to execute the wrapped method. It receives a String[] args which is sent from the CallReference and must be handled on a case-by-case basis depending on the required parameters of the wrapped method. To help the user with method parameters, requiredParams returns a string listing the required parameters of the wrapped method.

client.py-

Primitive client that connects to robot on port 8080. 

Issues-

-Communication quality between the roboRIO and client is sometimes unstable and results in timeouts

### CODE REVIEW

**Comment by PaulTerrasi** [comment]
@michaelsilver Can you try to figure out why the Travis build is failing with the new WPILib?

**Comment by PaulTerrasi** [comment]
@EdwardS2013 Please fix the issue with connection timeout errors and put all of the methods that outside classes will use into a single class. Other than that, LGTM!

**Comment by michaelsilver** [comment]
> @michaelsilver Can you try to figure out why the Travis build is failing with the new WPILib?

I'll get on this tonight, or latest tomorrow in the lab. If this PR is blocking progress, go ahead and merge. If you can live without merging this PR until tomorrow, wait and I'll fix the Travis issue in this branch before you merge.

**Comment by michaelsilver** [comment]
@PaulTerrasi fixed Travis :)

**Pull request merged**
